# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [4]:
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [7]:
print('The Diameter of {planet} is {diameter}  kilometers.'.format(planet='Earth', diameter=12742))

The Diameter of Earth is 12742  kilometers.


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [14]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b), axis = None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd


In [18]:
pd.DataFrame(index=np.arange(3), columns=np.arange(2))


0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
from datetime import date,timedelta

sdate = date(2023,1,1)
edate = date(2023,2,10)

def dates_between_two_dates(start_dates,  end_dates):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)

print(dates_between_two_dates(sdate, edate))


<generator object dates_between_two_dates at 0x000001D4E6213C80>


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [20]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
df = pd.DataFrame(lists,columns=['sno','names','number'])

In [22]:
print(df)

   sno names  number
0    1   aaa      22
1    2   bbb      25
2    3   ccc      24
