In [1]:
import numpy as np

In [2]:
## Create an array

a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
#checking dimension

a.ndim

1

In [5]:
a= np.array([[1,2,3,4,5],[2,3,7,5,8]])
a                                             #creating two dimesional array

array([[1, 2, 3, 4, 5],
       [2, 3, 7, 5, 8]])

In [6]:
a.ndim

2

In [9]:
# create a three dimensional array

a= np.array([[[1,2,3,4,5],[2,3,7,5,8],[7,8,9,5,4]]])
a 

array([[[1, 2, 3, 4, 5],
        [2, 3, 7, 5, 8],
        [7, 8, 9, 5, 4]]])

In [10]:
a.ndim

3

## Zero's and one's

In [11]:
var=np.zeros(10)

In [12]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
var1=np.ones(10)

In [16]:
var1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [18]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## functions

In [27]:
var=np.array([22,56,33,44])
var

array([22, 56, 33, 44])

In [28]:
type(var)

numpy.ndarray

In [29]:
var.argmax() #max value in index position

1

In [30]:
var.argmin() # min index value

0

In [31]:
var[2]

33

In [32]:
var[0]

22

In [33]:
var[3]

44

In [35]:
var

array([22, 56, 33, 44])

In [34]:
var[0:2]

array([22, 56])

In [40]:
var[1:3]

array([56, 33])

In [41]:
var[0:-1]

array([22, 56, 33])

In [44]:
arr4=np.array([1,2.0,4,5,7,8,9,5,3])
arr4

array([1., 2., 4., 5., 7., 8., 9., 5., 3.])

In [45]:
arr4.dtype

dtype('float64')

In [46]:
arr4.size

9

In [ ]:
## Create a numpy array with size 5 and datatype of float

In [47]:
arr5=np.array([1.0,2,3,4,5])
arr5

array([1., 2., 3., 4., 5.])

In [48]:
arr5.size

5

In [49]:
arr5.dtype

dtype('float64')

In [ ]:
# create a two dim array
# four arrays in the external array
# it should have two elements each

In [50]:
#dinesh

arr6=np.array([[1,2],[3,4],[5,6],[7,8]])
arr6

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
arr6.dtype

dtype('int32')

In [52]:
arr6.size

8

In [53]:
arr6.ndim

2

In [54]:
# Adithya
arr2=np.array([[1,2],[1,2],[2,3],[4,5]])
arr2

array([[1, 2],
       [1, 2],
       [2, 3],
       [4, 5]])

In [55]:
arr6.size

8

In [56]:
arr6.ndim

2

In [60]:
# Babisha
arr1=np.array([[4,8],[5,2],[4,8],[5,3]])
arr1

array([[4, 8],
       [5, 2],
       [4, 8],
       [5, 3]])

In [61]:
arr1.ndim

2

In [62]:
arr1.size

8

## Resize and reshape

In [64]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
a.ndim

1

In [72]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [88]:
b=a.reshape(6,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [89]:
b.shape

(6, 2)

In [75]:
a.max()

11

In [76]:
a.min()

0

In [78]:
x=[1,4,5,2,8]
x

[1, 4, 5, 2, 8]

In [79]:
np.sqrt(x)

array([1.        , 2.        , 2.23606798, 1.41421356, 2.82842712])

In [80]:
np.log(x)

array([0.        , 1.38629436, 1.60943791, 0.69314718, 2.07944154])

In [81]:
np.exp(x)

array([2.71828183e+00, 5.45981500e+01, 1.48413159e+02, 7.38905610e+00,
       2.98095799e+03])

In [90]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
a.shape

(12,)

## Transpose

In [92]:
b=a.reshape(6,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [94]:
a1=b.T
a1

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## Floor & Ceil

In [105]:
arr2=np.array([10.8,3.64,6.12,10.2])

In [106]:
arr2

array([10.8 ,  3.64,  6.12, 10.2 ])

In [103]:
np.floor(arr2)

array([10.,  3.,  6., 10.])

In [104]:
np.ceil(arr2)   # it is giving next integer value

array([11.,  4.,  7., 11.])

In [107]:
round_data= np.round(arr2)

In [108]:
round_data

array([11.,  4.,  6., 10.])

## Stacking

In [109]:
arr23=np.arange(10).reshape(2,5)

In [110]:
arr24=np.arange(20).reshape(4,5)

In [111]:
arr23

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [112]:
arr24

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [114]:
np.vstack((arr23,arr24))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [115]:
np.hstack((arr23,arr24))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

- ## For vstack(vertical) number of columns should be same and for hstack(horizondal) number of rows should be same for two arrays

## Numpy slit

In [117]:
arr28=np.arange(100).reshape(10,10)
arr28

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
np.vsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [119]:
np.hsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [ ]:
?# Create a numpy array with the shape of 20,10 and divide it into 2 equal parts horizondally

In [121]:
arr29=np.arange(200).reshape(20,10)
arr29

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [122]:
afte_split=np.hsplit(arr29,2)

In [123]:
afte_split

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,